name: "Setup action"
description: "Prepares for execution - set up Java, Node, npm, Gradle"

inputs:
  nodeVersion:
    description: "NodeJS Version"
    required: false
    default: "12"
  jdkVersion:
    description: "JDK version"
    required: false
    default: "8"

runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.jdkVersion }}
      uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: ${{ inputs.jdkVersion }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

    - name: "Setup Node"
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: "Install yarn"
      run: "npm install -g yarn"
      shell: bash
